apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: pelias-data-container
    name: pelias-data-container
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/pelias-data-container
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pelias-data-container
    name: pelias-data-container
  spec:
    replicas: 1
    selector:
      app: pelias-data-container
      deploymentconfig: pelias-data-container
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pelias-data-container
          deploymentconfig: pelias-data-container
      spec:
        nodeSelector:
          role: general
        containers:
        - image: hsldevcom/pelias-data-container
          name: pelias-data-container
          livenessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9200
            initialDelaySeconds: 120
            timeoutSeconds: 10
            periodSeconds: 2
          ports:
          - containerPort: 9200
            protocol: TCP
          - containerPort: 9300
            protocol: TCP
          resources:
            requests:
              memory: 1500Mi
          volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: pelias-data-container-volume-1
        volumes:
        - emptyDir: {}
          name: pelias-data-container-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pelias-data-container
        from:
          kind: ImageStreamTag
          name: pelias-data-container:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
