apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: navigator-server
    name: navigator-server
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/navigator-server
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: navigator-server
    name: navigator-server
  spec:
    replicas: 2
    selector:
      app: navigator-server
      deploymentconfig: navigator-server
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: navigator-server
          deploymentconfig: navigator-server
      spec:
        nodeSelector:
          mem: 8g
        containers:
        - image: hsldevcom/navigator-server
          name: navigator-server
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 2
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 1500Mi
            limits:
              memory: 2000Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - navigator-server
        from:
          kind: ImageStreamTag
          name: navigator-server:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
