apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: hsl-map-server
    name: hsl-map-server
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/hsl-map-server
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: hsl-map-server
    name: hsl-map-server
  spec:
    replicas: 2
    selector:
      app: hsl-map-server
      deploymentconfig: hsl-map-server
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hsl-map-server
          deploymentconfig: hsl-map-server
      spec:
        nodeSelector:
          mem: 8g
        containers:
        - env:
          - name: FONTSTACK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fontstack
                key: fontstackpassword
          - name: HSL_OTP_URL
            value: opentripplanner-hsl:8080/otp/routers/hsl/index/graphql
          - name: FINLAND_OTP_URL
            value: opentripplanner-finland:8080/otp/routers/finland/index/graphql
          - name: WALTTI_OTP_URL
            value: opentripplanner-waltti:8080/otp/routers/waltti/index/graphql
          image: hsldevcom/hsl-map-server
          name: hsl-map-server
          livenessProbe:
            httpGet:
              path: /hsl-map/index.json
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /hsl-map/index.json
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 1
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              memory: 2000Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - hsl-map-server
        from:
          kind: ImageStreamTag
          name: hsl-map-server:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
