apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui-default
    name: digitransit-ui-default
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: digitransit-ui-default
  status:
    loadBalancer: {}
kind: List
metadata: {}
