apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-site
    name: digitransit-site
  spec:
    dockerImageRepository: hsldevcom/digitransit-site
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-site
    name: digitransit-site
  spec:
    replicas: 2
    selector:
      app: digitransit-site
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: digitransit-site
      spec:
        nodeSelector:
          mem: 8g
        containers:
        - env:
          image: hsldevcom/digitransit-site
          name: digitransit-site
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              memory: 100Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - digitransit-site
        from:
          kind: ImageStreamTag
          name: digitransit-site:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
