apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: opentripplanner
    name: opentripplanner
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/opentripplanner
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: opentripplanner
    name: opentripplanner
  spec:
    replicas: 1
    selector:
      app: opentripplanner
      deploymentconfig: opentripplanner
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: opentripplanner
          deploymentconfig: opentripplanner
      spec:
        containers:
        - image: hsldevcom/opentripplanner
          name: opentripplanner
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: TCP
          resources:
            requests:
              memory: 7500Mi
          volumeMounts:
          - mountPath: /root/.m2
            name: opentripplanner-volume-1
        volumes:
        - emptyDir: {}
          name: opentripplanner-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - opentripplanner
        from:
          kind: ImageStreamTag
          name: opentripplanner:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
