apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: siri2gtfsrt
    name: siri2gtfsrt
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/siri2gtfsrt
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: siri2gtfsrt
    name: siri2gtfsrt
  spec:
    replicas: 1
    selector:
      app: siri2gtfsrt
      deploymentconfig: siri2gtfsrt
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: siri2gtfsrt
          deploymentconfig: siri2gtfsrt
      spec:
        nodeSelector:
          role: general
        containers:
        - env:
          - name: CHAIN_URL
            value: http://raildigitraffic2gtfsrt:8080/hsl
          - name: HSL_URL
            value: http://navigator-server:8080/siriaccess/vm/json
          - name: TRIP_UPDATE_URL
            value: http://hslalert:8080/
          image: hsldevcom/siri2gtfsrt
          name: siri2gtfsrt
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 150Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - siri2gtfsrt
        from:
          kind: ImageStreamTag
          name: siri2gtfsrt:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
