apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: siri2gtfsrt
    name: siri2gtfsrt
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: siri2gtfsrt
  status:
    loadBalancer: {}
kind: List
metadata: {}
