apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: pelias-api
    name: pelias-api
  spec:
    tags:
    - from:
        kind: DockerImage
        name: hsldevcom/pelias-api
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: pelias-api
    name: pelias-api
  spec:
    replicas: 1
    selector:
      app: pelias-api
      deploymentconfig: pelias-api
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: pelias-api
          deploymentconfig: pelias-api
      spec:
        nodeSelector:
          role: general
        containers:
        - image: hsldevcom/pelias-api
          name: pelias-api
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 800Mi
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - pelias-api
        from:
          kind: ImageStreamTag
          name: pelias-api:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
