apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui
    name: digitransit-ui
  spec:
    dockerImageRepository: hsldevcom/digitransit-ui
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui
    name: digitransit-ui
  spec:
    replicas: 1
    selector:
      app: digitransit-ui
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: digitransit-ui
      spec:
        containers:
        - env:
          - name: FONTSTACK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: fontstack
                name: fontstack_password
          image: hsldevcom/digitransit-ui
          name: digitransit-ui
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - digitransit-ui
        from:
          kind: ImageStreamTag
          name: digitransit-ui:latest
      type: ImageChange
  status: {}
kind: List
metadata: {}
