apiVersion: v1
items:

# Default
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui-default
    name: digitransit-ui-default
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: digitransit-ui-default
  status:
    loadBalancer: {}

# HSL
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui-hsl
    name: digitransit-ui-hsl
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: digitransit-ui-hsl
  status:
    loadBalancer: {}

# Joensuu
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui-joensuu
    name: digitransit-ui-joensuu
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: digitransit-ui-joensuu
  status:
    loadBalancer: {}

# Turku
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: digitransit-ui-turku
    name: digitransit-ui-turku
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: digitransit-ui-turku
  status:
    loadBalancer: {}

kind: List
metadata: {}
